# Site settings
# Create custom variables. accessible in the templates via {{site.myvariable}}.
title: Indra MX
email: vinoth.michaelxavier@gmail.com
description: Indra MX
baseurl: "/indra" # the subpath of your site, e.g. /blog
github_username: lookininward

# Build settings
markdown: kramdown

# Following will not be processed.
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: _sass
  style: compressed

# jekyll-minifier:
  # remove_intertag_spaces: true      # Default: false

include: ["_pages"]
